### ISSUE TITLE
Update Flatpak runtime

### ISSUE THREAD

**Issue by jjgalvez** [flathub/nl.lostboys.rollemup#3]
Please update flatpac, receiving the following when updating
runtime org.freedesktop.Platform branch 20.08 is end-of-life

**Comment by jjgalvez** [comment]
@TomaszGasior Just saw that you picked this up. Thanks in advance

**Comment by mrunar** [comment]
While downloading https://www.pro-linux.de/files/rollemup/Rollemup.tar.gz: Unacceptable TLS certificate

**Comment by TomaszGasior** [comment]
@mrunar This is not related to this issue. However, there is another issue about TLS certificate here: https://github.com/flathub/nl.lostboys.rollemup/issues/2. Please provide details there.
