### ISSUE TITLE
Include share=ipc access since the app has x11

### ISSUE THREAD

**Issue by bbhtt** [flathub/nl.lostboys.rollemup#7]
Not having this will be an error starting next week. See https://docs.flatpak.org/en/latest/sandbox-permissions.html#f1

**Comment by TomaszGasior** [comment]
The whole point of Flaptak is to provide stable and predictable  environment for application. I don't thing any changes should be required to keep the app working. Otherwise, it means Flatpak does not deliver what it should.

The linked documentation says:

> --share=ipc - Share IPC namespace with the host [1]
> This is not necessarily required, but without it the X11 shared memory extension will not work, which is very bad for X11 performance.

For now, I don't see any reason to apply that change.

Do you have any other documentation for the requirement of this kind of change?

**Comment by bbhtt** [comment]
We will make, not having it an error regardless, next week. You won't be able to merge updates if the build starts to fail on that.

I think you misunderstood, not having the permission will cause performance issues when the app is running on a X11 session

For Flatpak to provide a stable environment the app it needs to have the required permissions to work properly.

**Comment by TomaszGasior** [comment]
> For Flatpak to provide a stable environment the app it needs to have the required permissions to work properly.

To provide stable environment, there should be no requirement to change any permissions to make existing application still working.

If this new requirement only applies for merging updates, it's okay. What matters for me is to not break anything for the current state. Until I push new updates, everything should work without my intervention.

**Comment by TomaszGasior** [comment]
Rollemup is legacy software from late 90s. There won't be any updates here…

**Comment by bbhtt** [comment]
Not having it initially was an error on your part, it should've been present in the manifest from day 1.

This is not a new permission, it was introduced 9-10 years ago in Flatpak.

We are just enforcing it on Flathub so that people don't make the mistake again.

Any way, you do you.

**Comment by TomaszGasior** [comment]
> We are just enforcing it on Flathub so that people don't make the mistake again.

Ok, this actually is nice. 

The thing is: the app works 100% correctly right now and I don't want to change anything here. 

If there will be any update, I will be forced  by Flathub to add the parameter. Then, I will do that.
